name: Debian Package
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y debhelper dh-make build-essential
    - name: Build package
      run: |
        dpkg-buildpackage -us -uc
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: program-deb
        path: ../*.deb
