name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install -y autoconf automake libtool
    - name: Build and test
      run: |
        autoreconf -i
        ./configure
        make
        make check
